### ISSUE TITLE
Config doesn't support bomb ID changes

### ISSUE THREAD

**Issue by tara81** [Europia79/Demolition#2]
My config : 

#   # cmd toggle: /bomb debug
PlantTime: 6
DetonationTime: 40
DefuseTime: 6
TimerSound: LEVEL_UP
BombBlock: REDSTONE_BLOCK
BaseBlock: BREWING_STAND
BaseRadius: 3
FakeName: Bombs Planted Defused
ChangeFakeName: Not Implemented
MaxDamage: 50
DeltaDamage: 5
DamageRadius: 9
StartupDisplay: 3
DatabaseTable: BombArena
ShowHolograms: true
Debug: false

================

Still shows up as tnt. No matter what i change the BombBlock to, ive tried ID's and Material names.

**Comment by Europia79** [comment]
@tara81 

i couldn't replicate this bug. It worked for me: Meaning that the ```REDSTONE_BLOCK``` spawned instead of the default ```TNT```

**Comment by tara81** [comment]
what the heck then .  Why only me.

**Comment by Europia79** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

Those are all the valid values for ```BombBlock:``` and ```TimerSound:```

I would need more information to diagnose your problem. It would probably be best to screen share over Skype so that I could quickly take a look at various config files that may, or may not be relevant to the problem at hand. This way, it would save you the hassle of publicly pasting all your files.

**Comment by Europia79** [comment]
hold a ```REDSOTNE_BLOCK``` in your hand, then run the command

```
/bomb setconfig bombblock
```
