### ISSUE TITLE
Can't set default classes in onStart

### ISSUE THREAD

**Issue by c0wg0d** [Europia79/Demolition#4]
I have special kits for one of my bomb arena games.  There are 2 teams, and I want each team to automatically be assigned a particular kit.

If I shut the server down and put the following in my BombArena/arenas.yml file:

`params:
      onStart:
        giveClass:
          team1: bomber
          team2: sniper`

Then when the server starts back up, it is changed to this:

`onStart:
        giveClass:
          team0: sniper`

I have also tried setting it to be team0: bomber and team1: sniper but that doesn't work either.

NOTE: The formatting for the yml is correct in my file, I just don't know how to post it properly on github.

**Comment by c0wg0d** [comment]
I just realized I can separate the waiting rooms and then use kit signs in each waiting room as a workaround, but would still like to get this fixed if possible.

**Comment by Europia79** [comment]
This would be an issue with BattleArena where it reads ```team# - 1``` but incorrectly writes it back as ```team#``` instead of the correct number, which would be ```team# + 1```. An alternative solution would be to read & write ```team#``` both times.

Here's the code:
Reading via ```getTransitionOptions()```
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L523
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L623
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L634

Writing via ```saveParams()```
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L882
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L944
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/serializers/ConfigSerializer.java#L947

**Comment by Europia79** [comment]
Here's the download:
http://rainbowcraft.sytes.net/download/plugins/BattleArena/v3.9.10.6/
