### ISSUE TITLE
1.9.2 sound on bomb timer

### ISSUE THREAD

**Issue by trublud** [Europia79/Demolition#6]
IT seems to not count down when the bomb is placing, it says the sound errors out not found, is there a fix?

**Comment by trublud** [comment]
ITseems to not count down when the bomb is placing, it says the sound errors out not found, is there a fix?

**Comment by Europia79** [comment]
Can you paste your server log file into a pasting service like pastebin or hastebin ? And give me the link so that I can look thru the errors ?

**Comment by tara81** [comment]
BombArena : When opening a brewstand with tnt in inventory, theres no timer, no activation of bomb, no one can win by blwoing up a base.

**Comment by tara81** [comment]
Also : If a player has a compass in their inventory when they join the game, they lose their compass when they leave.

**Comment by tara81** [comment]
http://pastebin.com/22R1nwks Plant errors

**Comment by Europia79** [comment]
Yeah, that's the Sound error that I'm fixing now. Minecraft has changed the name of Sounds in 1.9... And BombArena was using the old 1.8 names... So Sound error breaks other code like planting & defusing, etc. It's a very easy fix. It's just time-consuming because I'm not going for the quick N easy fix... I'm completely squashing this problem once-and-for-all with a ```SoundAdapter```. Which will prevent similar problems in the future, and also make the code backwards-compatible & fowards-compatible.

**Comment by Europia79** [comment]
http://rainbowcraft.sytes.net/download/plugins/BombArena/v1.2.5/

BombArena v1.2.5 should fix this issue.
